/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universitysystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author DCN
 */
public class SalaryCalculate extends javax.swing.JFrame {

    ArrayList<String> fList= new ArrayList<>();    
    ArrayList<Integer> idsList= new ArrayList<>();
    ArrayList<String> nameList = new ArrayList<>();
    /**
     * Creates new form SalaryCalculate
     */
    public SalaryCalculate() {
        initComponents();
        fetchFacultyList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbFaculty = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        tfNumOfDays = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        tfApplyBonus = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbSalary = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tfRemarks = new javax.swing.JTextField();
        lbError = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cbBonusType = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        cbMonth = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnSalaryList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(120, 137, 146));
        jPanel1.setPreferredSize(new java.awt.Dimension(863, 505));

        jPanel2.setBackground(new java.awt.Color(207, 207, 207));

        jLabel23.setBackground(new java.awt.Color(6, 20, 27));
        jLabel23.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Calculate Salary");

        jLabel24.setBackground(new java.awt.Color(6, 20, 27));
        jLabel24.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Select Faculty");

        cbFaculty.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cbFaculty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        cbFaculty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFacultyActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(6, 20, 27));
        jLabel25.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Number of days worked");

        tfNumOfDays.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfNumOfDays.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        tfNumOfDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumOfDaysActionPerformed(evt);
            }
        });

        btnCalculate.setBackground(new java.awt.Color(6, 20, 27));
        btnCalculate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalculate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalculate.setMaximumSize(new java.awt.Dimension(64, 18));
        btnCalculate.setMinimumSize(new java.awt.Dimension(64, 18));
        btnCalculate.setPreferredSize(new java.awt.Dimension(64, 18));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(6, 20, 27));
        jLabel26.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Apply Bonus (%age)");

        tfApplyBonus.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfApplyBonus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        tfApplyBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApplyBonusActionPerformed(evt);
            }
        });

        jLabel27.setBackground(new java.awt.Color(6, 20, 27));
        jLabel27.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Calculated Salary:");

        lbSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSalary.setText("Rs.XX");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbSalary)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel28.setBackground(new java.awt.Color(6, 20, 27));
        jLabel28.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Add Remarks");

        tfRemarks.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfRemarks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        tfRemarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRemarksActionPerformed(evt);
            }
        });

        lbError.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        lbError.setForeground(new java.awt.Color(193, 55, 55));

        jLabel29.setBackground(new java.awt.Color(6, 20, 27));
        jLabel29.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Bonus Type");

        cbBonusType.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cbBonusType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "Festival Bonus", "Project Bonus", "Attendence Bonus", "Referral Bonus", "Milestone Bonus", "Spot Bonus" }));
        cbBonusType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        cbBonusType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel30.setBackground(new java.awt.Color(6, 20, 27));
        jLabel30.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Select Month");

        cbMonth.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cbMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        cbMonth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(169, 169, 169));
        jButton2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton2.setText("←");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 55, 69)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(6, 20, 27));
        btnSubmit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmit.setMaximumSize(new java.awt.Dimension(64, 18));
        btnSubmit.setMinimumSize(new java.awt.Dimension(64, 18));
        btnSubmit.setPreferredSize(new java.awt.Dimension(64, 18));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnSalaryList.setBackground(new java.awt.Color(6, 20, 27));
        btnSalaryList.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        btnSalaryList.setForeground(new java.awt.Color(255, 255, 255));
        btnSalaryList.setText("Check salary list");
        btnSalaryList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalaryList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalaryList.setMaximumSize(new java.awt.Dimension(64, 18));
        btnSalaryList.setMinimumSize(new java.awt.Dimension(64, 18));
        btnSalaryList.setPreferredSize(new java.awt.Dimension(64, 18));
        btnSalaryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel29))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfApplyBonus)
                                    .addComponent(cbBonusType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNumOfDays)
                                    .addComponent(cbMonth, 0, 155, Short.MAX_VALUE)))
                            .addComponent(cbFaculty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28)
                            .addComponent(tfRemarks)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnSalaryList, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(cbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(tfNumOfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(tfApplyBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(cbBonusType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalaryList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        if(tfNumOfDays.getText().isEmpty())
        {
            lbError.setText("Kindly enter valid information to proceed.");
        }
        else{
            lbError.setText("");
            Integer i = cbFaculty.getSelectedIndex();
            int selectedId = idsList.get(i);

            String sql = "select * from faculty where id = ?";
            
            try {
                Connection conn = ConnectionUtil.getInstance();
                PreparedStatement  pst = conn.prepareStatement(sql);
                pst.setInt(1, selectedId);
                ResultSet rs = pst.executeQuery();
                
                if(rs.next())
                {
                    int salary = rs.getInt("salary");
                    int days = Integer.parseInt(tfNumOfDays.getText());
                    int month;
                    int cbM = cbMonth.getSelectedIndex();
//                    String monthSelected = (String) cbMonth.getSelectedItem();
                    
                    month = switch (cbM) {
                        case 0, 2, 4, 6, 7, 9, 11 -> 31;
                        case 1 -> 28;
                        default -> 30;
                    };
                    double perDaySalary = salary / month;
                    double calculatedSalary = perDaySalary * days;
                    if(! (tfApplyBonus.getText().isEmpty()))
                    {                   
                        float bonus = Integer.parseInt(tfApplyBonus.getText());
//                        pst1.setString(4, String.valueOf(bonus));
//                        String bType = (String) cbBonusType.getSelectedItem();
//                        pst1.setString(5, bType);
                        calculatedSalary = calculatedSalary + (calculatedSalary * (bonus / 100));
                    }
//                    pst1.setString(3, String.valueOf(calculatedSalary));
                    if(! (tfRemarks.getText().isEmpty()))
                    {
//                        pst1.setString(6, tfRemarks.getText());
                    }
                    DecimalFormat df = new DecimalFormat("#.00");
                    String formattedSalary = df.format(calculatedSalary);
                    lbSalary.setText("Rs. "+ formattedSalary);
                }
                else
                {
                    lbError.setText("Error occured, please try again.");
                }
            }
            catch (SQLException ex){
                  Logger.getLogger(SalaryCalculate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void tfApplyBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApplyBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApplyBonusActionPerformed

    private void cbFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFacultyActionPerformed

    private void tfNumOfDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumOfDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumOfDaysActionPerformed

    private void tfRemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRemarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRemarksActionPerformed

    private void cbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMonthActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminLogin lp;
        lp = new AdminLogin();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Connection conn;
        try {
            if(tfNumOfDays.getText().isEmpty())
            {
                lbError.setText("Kindly enter number of days worked and calculate the salary first.");
            }
            else{
                conn = ConnectionUtil.getInstance();
            String insert = "INSERT INTO calculated_salary(faculty_id, name, month, salary, bonus, bonus_type, remarks, days_worked) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            String monthSelected = (String) cbMonth.getSelectedItem();
            String bonus = tfApplyBonus.getText();
            String bType = (String) cbBonusType.getSelectedItem();
            String calculatedSalary = lbSalary.getText();
            Integer i = cbFaculty.getSelectedIndex();
            int selectedId = idsList.get(i);
            String name = nameList.get(i);
            String numOfDays = tfNumOfDays.getText();
                
            PreparedStatement  pst1 = conn.prepareStatement(insert);
            pst1.setString(1, String.valueOf(selectedId));
            pst1.setString(3, monthSelected);
            pst1.setString(5, String.valueOf(bonus));
            pst1.setString(6, bType);
            pst1.setString(4, String.valueOf(calculatedSalary));
            pst1.setString(7, tfRemarks.getText());
            pst1.setString(2, name);
            pst1.setString(8,numOfDays);
        
            int a = pst1.executeUpdate();
                 
            if(a > 0)
            {
                lbError.setText("Information updated successfully.");
            }
            else
            {
                lbError.setText("Error occured, please try again.");
            }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(SalaryCalculate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnSalaryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryListActionPerformed
        // TODO add your handling code here:
        SalaryList s = new SalaryList();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalaryListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalaryCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalaryCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalaryCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalaryCalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalaryCalculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnSalaryList;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbBonusType;
    private javax.swing.JComboBox<String> cbFaculty;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbSalary;
    private javax.swing.JTextField tfApplyBonus;
    private javax.swing.JTextField tfNumOfDays;
    private javax.swing.JTextField tfRemarks;
    // End of variables declaration//GEN-END:variables

    private void fetchFacultyList() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
          try {
           
            Connection conn= ConnectionUtil.getInstance();
            
            if(conn==null)
            {
                System.out.println("Connection error");
            }
            else{
                    System.out.println("Connection established"); 
            }
            Statement st = conn.createStatement();
            ResultSet rs=  st.executeQuery("select * from faculty");

        
          
//          ResultSet rs2 =  st.executeQuery("select * from users");
            while(rs.next())
            {
            fList.add(rs.getInt("id")+"-"+rs.getString("name"));
            idsList.add(rs.getInt("id"));
            nameList.add(rs.getString("name"));

            }
            String [] arr = new String[fList.size()];
            int i=0;
            for(String item :fList)
            {
                arr[i]= item;
                i++;
            }
            ComboBoxModel model = new DefaultComboBoxModel(arr);
            cbFaculty.setModel(model);
        }  catch (SQLException ex) {
            Logger.getLogger(StudentsList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }

