/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universitysystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DCN
 */
public class StudentRegister extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegister
     */
    public StudentRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfFname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfDob = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfAadhar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfClass_x = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfClass_xii = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbCourse = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbBranch = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel7.setBackground(new java.awt.Color(6, 20, 27));
        jLabel7.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contact Number");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(155, 168, 171));
        jPanel1.setFocusTraversalPolicyProvider(true);

        jPanel2.setBackground(new java.awt.Color(204, 208, 207));

        jLabel1.setBackground(new java.awt.Color(6, 20, 27));
        jLabel1.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register a Student");

        jLabel3.setBackground(new java.awt.Color(6, 20, 27));
        jLabel3.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name");

        tfName.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfName.setForeground(new java.awt.Color(6, 20, 27));
        tfName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfName.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(6, 20, 27));
        jLabel4.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Date of birth");

        tfFname.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfFname.setForeground(new java.awt.Color(6, 20, 27));
        tfFname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfFname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfFname.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFnameActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(6, 20, 27));
        jLabel5.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contact Number");

        tfMname.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfMname.setForeground(new java.awt.Color(6, 20, 27));
        tfMname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfMname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfMname.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfMname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMnameActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(6, 20, 27));
        jLabel6.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mother's Name");

        tfContact.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfContact.setForeground(new java.awt.Color(6, 20, 27));
        tfContact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfContact.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfContact.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContactActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(6, 20, 27));
        jLabel8.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Address");

        tfAddress.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfAddress.setForeground(new java.awt.Color(6, 20, 27));
        tfAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfAddress.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(6, 20, 27));
        jLabel9.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Father's Name");

        tfDob.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfDob.setForeground(new java.awt.Color(6, 20, 27));
        tfDob.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfDob.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfDob.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDobActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(6, 20, 27));
        jLabel10.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Password");

        tfPassword.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(6, 20, 27));
        tfPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfPassword.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(6, 20, 27));
        jLabel11.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Email");

        tfAadhar.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfAadhar.setForeground(new java.awt.Color(6, 20, 27));
        tfAadhar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfAadhar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfAadhar.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfAadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAadharActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(6, 20, 27));
        jLabel12.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Class X Score");

        tfClass_x.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfClass_x.setForeground(new java.awt.Color(6, 20, 27));
        tfClass_x.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfClass_x.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfClass_x.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfClass_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClass_xActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(6, 20, 27));
        jLabel13.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Class XII Score");

        tfClass_xii.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfClass_xii.setForeground(new java.awt.Color(6, 20, 27));
        tfClass_xii.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 20, 27), 1, true));
        tfClass_xii.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfClass_xii.setMargin(new java.awt.Insets(10, 20, 10, 10));
        tfClass_xii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClass_xiiActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(6, 20, 27));
        jLabel14.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Course");

        cbCourse.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "BBA", "MBA", "B.Tech", "M.Tech", "BCom", "MCom", "BA", "MA", " " }));
        cbCourse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        cbCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setBackground(new java.awt.Color(6, 20, 27));
        jLabel15.setFont(new java.awt.Font("Elephant", 0, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Branch");

        cbBranch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Electronics", "Mechanical", "Civil", "Accounting", "Buisness Analytics", "Finance", "Human Resources", "Entrepreneurship", "Marketing" }));
        cbBranch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 20, 27)));
        cbBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBranchActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(6, 20, 27));
        btnSubmit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmit.setMaximumSize(new java.awt.Dimension(64, 18));
        btnSubmit.setMinimumSize(new java.awt.Dimension(64, 18));
        btnSubmit.setPreferredSize(new java.awt.Dimension(64, 18));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lbError.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        lbError.setForeground(new java.awt.Color(193, 55, 55));

        jButton2.setBackground(new java.awt.Color(169, 169, 169));
        jButton2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jButton2.setText("←");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 55, 69)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(26, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfMname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel14))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfClass_x, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                                .addComponent(cbCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(111, 111, 111)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfClass_xii)
                                    .addComponent(tfDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(tfFname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(tfAadhar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(cbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbError, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfName)
                    .addComponent(tfFname)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tfMname))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tfDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tfContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(tfAadhar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tfPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfClass_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfClass_xii))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lbError, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFnameActionPerformed

    private void tfMnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMnameActionPerformed

    private void tfContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContactActionPerformed
        // TODO add your handlintfNamehere:
    }//GEN-LAST:event_tfContactActionPerformed

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void tfDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDobActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfAadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAadharActionPerformed

    private void tfClass_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClass_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClass_xActionPerformed

    private void tfClass_xiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClass_xiiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfClass_xiiActionPerformed

    private void cbBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBranchActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(tfPassword.getText().isEmpty() || tfName.getText().isEmpty() || tfAddress.getText().isEmpty() || tfClass_x.getText().isEmpty() || tfClass_xii.getText().isEmpty() || tfMname.getText().isEmpty() || tfFname.getText().isEmpty() || tfAadhar.getText().isEmpty() || tfDob.getText().isEmpty() || tfContact.getText().isEmpty())
        {
            lbError.setText("All fields are required.");
        }
        else{
            lbError.setText("");
            String name = tfName.getText();
            String fname = tfFname.getText();
            String mname = tfMname.getText();
            String dob = tfDob.getText();
            String contact = tfContact.getText();
            String email = tfAadhar.getText();
            String address = tfAddress.getText();
            String password = tfPassword.getText();
            String class_x = tfClass_x.getText();
            String class_xii = tfClass_xii.getText();
            String branch = (String) cbBranch.getSelectedItem();
            String course = (String) cbCourse.getSelectedItem();
            
            String sql = "INSERT INTO students (name, contact, fname, mname, dob, password, address, email, class_x, class_xii, course, branch) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            try {
                Connection conn = ConnectionUtil.getInstance();
                PreparedStatement  pst = conn.prepareStatement(sql);
                 pst.setString(1, name);
                 pst.setString(2,contact);
                 pst.setString(3, fname);
                 pst.setString(4, mname);
                 pst.setString(5, dob);
                 pst.setString(6, password);
                 pst.setString(7, address);
                 pst.setString(8, email);
                 pst.setString(9, class_x);
                 pst.setString(10, class_xii);
                 pst.setString(11, course);
                 pst.setString(12, branch);
                 int a = pst.executeUpdate();
                 
                 if(a > 0)
                 {
                     lbError.setText("You have successfully registered!");
                 }
                 else
                 {
                     lbError.setText("Error in registeration, please try again.");
                 }
            } 
            catch (SQLException ex) {
                Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, ex);
            }
}
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AdminLogin lp;
        lp = new AdminLogin();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbBranch;
    private javax.swing.JComboBox<String> cbCourse;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbError;
    private javax.swing.JTextField tfAadhar;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfClass_x;
    private javax.swing.JTextField tfClass_xii;
    private javax.swing.JTextField tfContact;
    private javax.swing.JTextField tfDob;
    private javax.swing.JTextField tfFname;
    private javax.swing.JTextField tfMname;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPassword;
    // End of variables declaration//GEN-END:variables
}
